build:
  image: golang:1.5
  environment:
    - CGO_ENABLED=0
  commands:
    - make deps
    - make vet
    - make build
    - make test

    
publish:
  docker:
    registry: docker.ca.bestbuy.com:5000
    repo: drone-harbour-test
    tag: latest
    insecure: true
    when:
      branch: master
