build:
  image: golang:1.5
  environment:
    - CGO_ENABLED=0
  commands:
    - make deps
    - make vet
    - make build
    - make test

    
publish:
  docker:
    repo: docker.ca.bestbuy.com:5000/drone-harbour
    tag: latest
    when:
      branch: master
